# Makefile.in generated by automake 1.15.1 from Makefile.am.
# Makefile.  Generated from Makefile.in by configure.

# Copyright (C) 1994-2017 Free Software Foundation, Inc.

# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.




am__is_gnu_make = { \
  if test -z '$(MAKELEVEL)'; then \
    false; \
  elif test -n '$(MAKE_HOST)'; then \
    true; \
  elif test -n '$(MAKE_VERSION)' && test -n '$(CURDIR)'; then \
    true; \
  else \
    false; \
  fi; \
}
am__make_running_with_option = \
  case $${target_option-} in \
      ?) ;; \
      *) echo "am__make_running_with_option: internal error: invalid" \
              "target option '$${target_option-}' specified" >&2; \
         exit 1;; \
  esac; \
  has_opt=no; \
  sane_makeflags=$$MAKEFLAGS; \
  if $(am__is_gnu_make); then \
    sane_makeflags=$$MFLAGS; \
  else \
    case $$MAKEFLAGS in \
      *\\[\ \	]*) \
        bs=\\; \
        sane_makeflags=`printf '%s\n' "$$MAKEFLAGS" \
          | sed "s/$$bs$$bs[$$bs $$bs	]*//g"`;; \
    esac; \
  fi; \
  skip_next=no; \
  strip_trailopt () \
  { \
    flg=`printf '%s\n' "$$flg" | sed "s/$$1.*$$//"`; \
  }; \
  for flg in $$sane_makeflags; do \
    test $$skip_next = yes && { skip_next=no; continue; }; \
    case $$flg in \
      *=*|--*) continue;; \
        -*I) strip_trailopt 'I'; skip_next=yes;; \
      -*I?*) strip_trailopt 'I';; \
        -*O) strip_trailopt 'O'; skip_next=yes;; \
      -*O?*) strip_trailopt 'O';; \
        -*l) strip_trailopt 'l'; skip_next=yes;; \
      -*l?*) strip_trailopt 'l';; \
      -[dEDm]) skip_next=yes;; \
      -[JT]) skip_next=yes;; \
    esac; \
    case $$flg in \
      *$$target_option*) has_opt=yes; break;; \
    esac; \
  done; \
  test $$has_opt = yes
am__make_dryrun = (target_option=n; $(am__make_running_with_option))
am__make_keepgoing = (target_option=k; $(am__make_running_with_option))
pkgdatadir = $(datadir)/nova
pkgincludedir = $(includedir)/nova
pkglibdir = $(libdir)/nova
pkglibexecdir = $(libexecdir)/nova
am__cd = CDPATH="$${ZSH_VERSION+.}$(PATH_SEPARATOR)" && cd
install_sh_DATA = $(install_sh) -c -m 644
install_sh_PROGRAM = $(install_sh) -c
install_sh_SCRIPT = $(install_sh) -c
INSTALL_HEADER = $(INSTALL_DATA)
transform = $(program_transform_name)
NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
bin_PROGRAMS = nova$(EXEEXT)
subdir = .
ACLOCAL_M4 = $(top_srcdir)/aclocal.m4
am__aclocal_m4_deps = $(top_srcdir)/configure.ac
am__configure_deps = $(am__aclocal_m4_deps) $(CONFIGURE_DEPENDENCIES) \
	$(ACLOCAL_M4)
DIST_COMMON = $(srcdir)/Makefile.am $(top_srcdir)/configure \
	$(am__configure_deps) $(am__DIST_COMMON)
am__CONFIG_DISTCLEAN_FILES = config.status config.cache config.log \
 configure.lineno config.status.lineno
mkinstalldirs = $(install_sh) -d
CONFIG_CLEAN_FILES =
CONFIG_CLEAN_VPATH_FILES =
am__installdirs = "$(DESTDIR)$(bindir)"
PROGRAMS = $(bin_PROGRAMS)
am__dirstamp = $(am__leading_dot)dirstamp
am_nova_OBJECTS = src/nova-Error.$(OBJEXT) \
	src/nova-Expression.$(OBJEXT) src/nova-Interpreter.$(OBJEXT) \
	src/nova-Lexer.$(OBJEXT) src/nova-ParseHelper.$(OBJEXT) \
	src/nova-Parser.$(OBJEXT) src/nova-Position.$(OBJEXT) \
	src/nova-shell.$(OBJEXT) src/nova-Statement.$(OBJEXT) \
	src/nova-SymbolTable.$(OBJEXT) src/nova-Token.$(OBJEXT) \
	src/nova-types.$(OBJEXT)
nova_OBJECTS = $(am_nova_OBJECTS)
nova_LDADD = $(LDADD)
nova_LINK = $(CXXLD) $(nova_CXXFLAGS) $(CXXFLAGS) $(AM_LDFLAGS) \
	$(LDFLAGS) -o $@
AM_V_P = $(am__v_P_$(V))
am__v_P_ = $(am__v_P_$(AM_DEFAULT_VERBOSITY))
am__v_P_0 = false
am__v_P_1 = :
AM_V_GEN = $(am__v_GEN_$(V))
am__v_GEN_ = $(am__v_GEN_$(AM_DEFAULT_VERBOSITY))
am__v_GEN_0 = @echo "  GEN     " $@;
am__v_GEN_1 = 
AM_V_at = $(am__v_at_$(V))
am__v_at_ = $(am__v_at_$(AM_DEFAULT_VERBOSITY))
am__v_at_0 = @
am__v_at_1 = 
DEFAULT_INCLUDES = -I.
depcomp = $(SHELL) $(top_srcdir)/config/depcomp
am__depfiles_maybe = depfiles
am__mv = mv -f
AM_V_lt = $(am__v_lt_$(V))
am__v_lt_ = $(am__v_lt_$(AM_DEFAULT_VERBOSITY))
am__v_lt_0 = --silent
am__v_lt_1 = 
CXXCOMPILE = $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) \
	$(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS)
AM_V_CXX = $(am__v_CXX_$(V))
am__v_CXX_ = $(am__v_CXX_$(AM_DEFAULT_VERBOSITY))
am__v_CXX_0 = @echo "  CXX     " $@;
am__v_CXX_1 = 
CXXLD = $(CXX)
CXXLINK = $(CXXLD) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_LDFLAGS) $(LDFLAGS) \
	-o $@
AM_V_CXXLD = $(am__v_CXXLD_$(V))
am__v_CXXLD_ = $(am__v_CXXLD_$(AM_DEFAULT_VERBOSITY))
am__v_CXXLD_0 = @echo "  CXXLD   " $@;
am__v_CXXLD_1 = 
SOURCES = $(nova_SOURCES)
DIST_SOURCES = $(nova_SOURCES)
am__can_run_installinfo = \
  case $$AM_UPDATE_INFO_DIR in \
    n|no|NO) false;; \
    *) (install-info --version) >/dev/null 2>&1;; \
  esac
am__tagged_files = $(HEADERS) $(SOURCES) $(TAGS_FILES) $(LISP)
# Read a list of newline-separated strings from the standard input,
# and print each of them once, without duplicates.  Input order is
# *not* preserved.
am__uniquify_input = $(AWK) '\
  BEGIN { nonempty = 0; } \
  { items[$$0] = 1; nonempty = 1; } \
  END { if (nonempty) { for (i in items) print i; }; } \
'
# Make sure the list of sources is unique.  This is necessary because,
# e.g., the same source file might be shared among _SOURCES variables
# for different programs/libraries.
am__define_uniq_tagged_files = \
  list='$(am__tagged_files)'; \
  unique=`for i in $$list; do \
    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
  done | $(am__uniquify_input)`
ETAGS = etags
CTAGS = ctags
CSCOPE = cscope
AM_RECURSIVE_TARGETS = cscope
am__DIST_COMMON = $(srcdir)/Makefile.in $(top_srcdir)/config/compile \
	$(top_srcdir)/config/depcomp $(top_srcdir)/config/install-sh \
	$(top_srcdir)/config/missing config/compile config/depcomp \
	config/install-sh config/missing
DISTFILES = $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST)
distdir = $(PACKAGE)-$(VERSION)
top_distdir = $(distdir)
am__remove_distdir = \
  if test -d "$(distdir)"; then \
    find "$(distdir)" -type d ! -perm -200 -exec chmod u+w {} ';' \
      && rm -rf "$(distdir)" \
      || { sleep 5 && rm -rf "$(distdir)"; }; \
  else :; fi
am__post_remove_distdir = $(am__remove_distdir)
DIST_ARCHIVES = $(distdir).tar.gz
GZIP_ENV = --best
DIST_TARGETS = dist-gzip
distuninstallcheck_listfiles = find . -type f -print
am__distuninstallcheck_listfiles = $(distuninstallcheck_listfiles) \
  | sed 's|^\./|$(prefix)/|' | grep -v '$(infodir)/dir$$'
distcleancheck_listfiles = find . -type f -print
ACLOCAL = ${SHELL} /u1/svishnu/fun/Nova/config/missing aclocal-1.15
AMTAR = $${TAR-tar}
AM_DEFAULT_VERBOSITY = 1
AUTOCONF = ${SHELL} /u1/svishnu/fun/Nova/config/missing autoconf
AUTOHEADER = ${SHELL} /u1/svishnu/fun/Nova/config/missing autoheader
AUTOMAKE = ${SHELL} /u1/svishnu/fun/Nova/config/missing automake-1.15
AWK = gawk
CC = gcc
CCDEPMODE = depmode=gcc3
CFLAGS = -g -O2
CPP = gcc -E
CPPFLAGS = 
CXX = g++
CXXDEPMODE = depmode=gcc3
CXXFLAGS = -g -O2
CYGPATH_W = echo
DEFS = -DPACKAGE_NAME=\"nova\" -DPACKAGE_TARNAME=\"nova\" -DPACKAGE_VERSION=\"0.1\" -DPACKAGE_STRING=\"nova\ 0.1\" -DPACKAGE_BUGREPORT=\"srihari.vishnu@gmail.com\" -DPACKAGE_URL=\"\" -DPACKAGE=\"nova\" -DVERSION=\"0.1\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1
DEPDIR = .deps
ECHO_C = 
ECHO_N = -n
ECHO_T = 
EGREP = /bin/grep -E
EXEEXT = 
GREP = /bin/grep
INSTALL = /usr/bin/install -c
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_PROGRAM = ${INSTALL}
INSTALL_SCRIPT = ${INSTALL}
INSTALL_STRIP_PROGRAM = $(install_sh) -c -s
LDFLAGS = 
LIBOBJS = 
LIBS = 
LTLIBOBJS = 
MAKEINFO = ${SHELL} /u1/svishnu/fun/Nova/config/missing makeinfo
MKDIR_P = /bin/mkdir -p
OBJEXT = o
PACKAGE = nova
PACKAGE_BUGREPORT = srihari.vishnu@gmail.com
PACKAGE_NAME = nova
PACKAGE_STRING = nova 0.1
PACKAGE_TARNAME = nova
PACKAGE_URL = 
PACKAGE_VERSION = 0.1
PATH_SEPARATOR = :
SET_MAKE = 
SHELL = /bin/bash
STRIP = 
VERSION = 0.1
abs_builddir = /u1/svishnu/fun/Nova
abs_srcdir = /u1/svishnu/fun/Nova
abs_top_builddir = /u1/svishnu/fun/Nova
abs_top_srcdir = /u1/svishnu/fun/Nova
ac_ct_CC = gcc
ac_ct_CXX = g++
am__include = include
am__leading_dot = .
am__quote = 
am__tar = $${TAR-tar} chof - "$$tardir"
am__untar = $${TAR-tar} xf -
bindir = ${exec_prefix}/bin
build_alias = 
builddir = .
datadir = ${datarootdir}
datarootdir = ${prefix}/share
docdir = ${datarootdir}/doc/${PACKAGE_TARNAME}
dvidir = ${docdir}
exec_prefix = ${prefix}
host_alias = 
htmldir = ${docdir}
includedir = ${prefix}/include
infodir = ${datarootdir}/info
install_sh = ${SHELL} /u1/svishnu/fun/Nova/config/install-sh
libdir = ${exec_prefix}/lib
libexecdir = ${exec_prefix}/libexec
localedir = ${datarootdir}/locale
localstatedir = ${prefix}/var
mandir = ${datarootdir}/man
mkdir_p = $(MKDIR_P)
oldincludedir = /usr/include
pdfdir = ${docdir}
prefix = /usr/local
program_transform_name = s,x,x,
psdir = ${docdir}
runstatedir = ${localstatedir}/run
sbindir = ${exec_prefix}/sbin
sharedstatedir = ${prefix}/com
srcdir = .
sysconfdir = ${prefix}/etc
target_alias = 
top_build_prefix = 
top_builddir = .
top_srcdir = .
AUTOMAKE_OPTIONS = foreign

# Instruct aclocal to check the cfg directory for
# extra macros
ACLOCAL_AMFLAGS = -I config
EXTRA_DIST = include/ 
AM_CXXFLAGS = -I$(top_srcdir)/include/ -std="c++17" -g
nova_CXXFLAGS = $(AM_CXXFLAGS)
nova_SOURCES = src/Error.cpp src/Expression.cpp src/Interpreter.cpp src/Lexer.cpp src/ParseHelper.cpp src/Parser.cpp src/Position.cpp src/shell.cpp src/Statement.cpp src/SymbolTable.cpp src/Token.cpp src/types.cpp 
all: all-am

.SUFFIXES:
.SUFFIXES: .cpp .o .obj
am--refresh: Makefile
	@:
$(srcdir)/Makefile.in:  $(srcdir)/Makefile.am  $(am__configure_deps)
	@for dep in $?; do \
	  case '$(am__configure_deps)' in \
	    *$$dep*) \
	      echo ' cd $(srcdir) && $(AUTOMAKE) --foreign'; \
	      $(am__cd) $(srcdir) && $(AUTOMAKE) --foreign \
		&& exit 0; \
	      exit 1;; \
	  esac; \
	done; \
	echo ' cd $(top_srcdir) && $(AUTOMAKE) --foreign Makefile'; \
	$(am__cd) $(top_srcdir) && \
	  $(AUTOMAKE) --foreign Makefile
Makefile: $(srcdir)/Makefile.in $(top_builddir)/config.status
	@case '$?' in \
	  *config.status*) \
	    echo ' $(SHELL) ./config.status'; \
	    $(SHELL) ./config.status;; \
	  *) \
	    echo ' cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__depfiles_maybe)'; \
	    cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__depfiles_maybe);; \
	esac;

$(top_builddir)/config.status: $(top_srcdir)/configure $(CONFIG_STATUS_DEPENDENCIES)
	$(SHELL) ./config.status --recheck

$(top_srcdir)/configure:  $(am__configure_deps)
	$(am__cd) $(srcdir) && $(AUTOCONF)
$(ACLOCAL_M4):  $(am__aclocal_m4_deps)
	$(am__cd) $(srcdir) && $(ACLOCAL) $(ACLOCAL_AMFLAGS)
$(am__aclocal_m4_deps):
install-binPROGRAMS: $(bin_PROGRAMS)
	@$(NORMAL_INSTALL)
	@list='$(bin_PROGRAMS)'; test -n "$(bindir)" || list=; \
	if test -n "$$list"; then \
	  echo " $(MKDIR_P) '$(DESTDIR)$(bindir)'"; \
	  $(MKDIR_P) "$(DESTDIR)$(bindir)" || exit 1; \
	fi; \
	for p in $$list; do echo "$$p $$p"; done | \
	sed 's/$(EXEEXT)$$//' | \
	while read p p1; do if test -f $$p \
	  ; then echo "$$p"; echo "$$p"; else :; fi; \
	done | \
	sed -e 'p;s,.*/,,;n;h' \
	    -e 's|.*|.|' \
	    -e 'p;x;s,.*/,,;s/$(EXEEXT)$$//;$(transform);s/$$/$(EXEEXT)/' | \
	sed 'N;N;N;s,\n, ,g' | \
	$(AWK) 'BEGIN { files["."] = ""; dirs["."] = 1 } \
	  { d=$$3; if (dirs[d] != 1) { print "d", d; dirs[d] = 1 } \
	    if ($$2 == $$4) files[d] = files[d] " " $$1; \
	    else { print "f", $$3 "/" $$4, $$1; } } \
	  END { for (d in files) print "f", d, files[d] }' | \
	while read type dir files; do \
	    if test "$$dir" = .; then dir=; else dir=/$$dir; fi; \
	    test -z "$$files" || { \
	      echo " $(INSTALL_PROGRAM_ENV) $(INSTALL_PROGRAM) $$files '$(DESTDIR)$(bindir)$$dir'"; \
	      $(INSTALL_PROGRAM_ENV) $(INSTALL_PROGRAM) $$files "$(DESTDIR)$(bindir)$$dir" || exit $$?; \
	    } \
	; done

uninstall-binPROGRAMS:
	@$(NORMAL_UNINSTALL)
	@list='$(bin_PROGRAMS)'; test -n "$(bindir)" || list=; \
	files=`for p in $$list; do echo "$$p"; done | \
	  sed -e 'h;s,^.*/,,;s/$(EXEEXT)$$//;$(transform)' \
	      -e 's/$$/$(EXEEXT)/' \
	`; \
	test -n "$$list" || exit 0; \
	echo " ( cd '$(DESTDIR)$(bindir)' && rm -f" $$files ")"; \
	cd "$(DESTDIR)$(bindir)" && rm -f $$files

clean-binPROGRAMS:
	-test -z "$(bin_PROGRAMS)" || rm -f $(bin_PROGRAMS)
src/$(am__dirstamp):
	@$(MKDIR_P) src
	@: > src/$(am__dirstamp)
src/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) src/$(DEPDIR)
	@: > src/$(DEPDIR)/$(am__dirstamp)
src/nova-Error.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/nova-Expression.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/nova-Interpreter.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/nova-Lexer.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/nova-ParseHelper.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/nova-Parser.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/nova-Position.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/nova-shell.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/nova-Statement.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/nova-SymbolTable.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/nova-Token.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/nova-types.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)

nova$(EXEEXT): $(nova_OBJECTS) $(nova_DEPENDENCIES) $(EXTRA_nova_DEPENDENCIES) 
	@rm -f nova$(EXEEXT)
	$(AM_V_CXXLD)$(nova_LINK) $(nova_OBJECTS) $(nova_LDADD) $(LIBS)

mostlyclean-compile:
	-rm -f *.$(OBJEXT)
	-rm -f src/*.$(OBJEXT)

distclean-compile:
	-rm -f *.tab.c

include src/$(DEPDIR)/nova-Error.Po
include src/$(DEPDIR)/nova-Expression.Po
include src/$(DEPDIR)/nova-Interpreter.Po
include src/$(DEPDIR)/nova-Lexer.Po
include src/$(DEPDIR)/nova-ParseHelper.Po
include src/$(DEPDIR)/nova-Parser.Po
include src/$(DEPDIR)/nova-Position.Po
include src/$(DEPDIR)/nova-Statement.Po
include src/$(DEPDIR)/nova-SymbolTable.Po
include src/$(DEPDIR)/nova-Token.Po
include src/$(DEPDIR)/nova-shell.Po
include src/$(DEPDIR)/nova-types.Po

.cpp.o:
	$(AM_V_CXX)depbase=`echo $@ | sed 's|[^/]*$$|$(DEPDIR)/&|;s|\.o$$||'`;\
	$(CXXCOMPILE) -MT $@ -MD -MP -MF $$depbase.Tpo -c -o $@ $< &&\
	$(am__mv) $$depbase.Tpo $$depbase.Po
#	$(AM_V_CXX)source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXXCOMPILE) -c -o $@ $<

.cpp.obj:
	$(AM_V_CXX)depbase=`echo $@ | sed 's|[^/]*$$|$(DEPDIR)/&|;s|\.obj$$||'`;\
	$(CXXCOMPILE) -MT $@ -MD -MP -MF $$depbase.Tpo -c -o $@ `$(CYGPATH_W) '$<'` &&\
	$(am__mv) $$depbase.Tpo $$depbase.Po
#	$(AM_V_CXX)source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXXCOMPILE) -c -o $@ `$(CYGPATH_W) '$<'`

src/nova-Error.o: src/Error.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(nova_CXXFLAGS) $(CXXFLAGS) -MT src/nova-Error.o -MD -MP -MF src/$(DEPDIR)/nova-Error.Tpo -c -o src/nova-Error.o `test -f 'src/Error.cpp' || echo '$(srcdir)/'`src/Error.cpp
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/nova-Error.Tpo src/$(DEPDIR)/nova-Error.Po
#	$(AM_V_CXX)source='src/Error.cpp' object='src/nova-Error.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(nova_CXXFLAGS) $(CXXFLAGS) -c -o src/nova-Error.o `test -f 'src/Error.cpp' || echo '$(srcdir)/'`src/Error.cpp

src/nova-Error.obj: src/Error.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(nova_CXXFLAGS) $(CXXFLAGS) -MT src/nova-Error.obj -MD -MP -MF src/$(DEPDIR)/nova-Error.Tpo -c -o src/nova-Error.obj `if test -f 'src/Error.cpp'; then $(CYGPATH_W) 'src/Error.cpp'; else $(CYGPATH_W) '$(srcdir)/src/Error.cpp'; fi`
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/nova-Error.Tpo src/$(DEPDIR)/nova-Error.Po
#	$(AM_V_CXX)source='src/Error.cpp' object='src/nova-Error.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(nova_CXXFLAGS) $(CXXFLAGS) -c -o src/nova-Error.obj `if test -f 'src/Error.cpp'; then $(CYGPATH_W) 'src/Error.cpp'; else $(CYGPATH_W) '$(srcdir)/src/Error.cpp'; fi`

src/nova-Expression.o: src/Expression.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(nova_CXXFLAGS) $(CXXFLAGS) -MT src/nova-Expression.o -MD -MP -MF src/$(DEPDIR)/nova-Expression.Tpo -c -o src/nova-Expression.o `test -f 'src/Expression.cpp' || echo '$(srcdir)/'`src/Expression.cpp
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/nova-Expression.Tpo src/$(DEPDIR)/nova-Expression.Po
#	$(AM_V_CXX)source='src/Expression.cpp' object='src/nova-Expression.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(nova_CXXFLAGS) $(CXXFLAGS) -c -o src/nova-Expression.o `test -f 'src/Expression.cpp' || echo '$(srcdir)/'`src/Expression.cpp

src/nova-Expression.obj: src/Expression.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(nova_CXXFLAGS) $(CXXFLAGS) -MT src/nova-Expression.obj -MD -MP -MF src/$(DEPDIR)/nova-Expression.Tpo -c -o src/nova-Expression.obj `if test -f 'src/Expression.cpp'; then $(CYGPATH_W) 'src/Expression.cpp'; else $(CYGPATH_W) '$(srcdir)/src/Expression.cpp'; fi`
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/nova-Expression.Tpo src/$(DEPDIR)/nova-Expression.Po
#	$(AM_V_CXX)source='src/Expression.cpp' object='src/nova-Expression.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(nova_CXXFLAGS) $(CXXFLAGS) -c -o src/nova-Expression.obj `if test -f 'src/Expression.cpp'; then $(CYGPATH_W) 'src/Expression.cpp'; else $(CYGPATH_W) '$(srcdir)/src/Expression.cpp'; fi`

src/nova-Interpreter.o: src/Interpreter.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(nova_CXXFLAGS) $(CXXFLAGS) -MT src/nova-Interpreter.o -MD -MP -MF src/$(DEPDIR)/nova-Interpreter.Tpo -c -o src/nova-Interpreter.o `test -f 'src/Interpreter.cpp' || echo '$(srcdir)/'`src/Interpreter.cpp
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/nova-Interpreter.Tpo src/$(DEPDIR)/nova-Interpreter.Po
#	$(AM_V_CXX)source='src/Interpreter.cpp' object='src/nova-Interpreter.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(nova_CXXFLAGS) $(CXXFLAGS) -c -o src/nova-Interpreter.o `test -f 'src/Interpreter.cpp' || echo '$(srcdir)/'`src/Interpreter.cpp

src/nova-Interpreter.obj: src/Interpreter.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(nova_CXXFLAGS) $(CXXFLAGS) -MT src/nova-Interpreter.obj -MD -MP -MF src/$(DEPDIR)/nova-Interpreter.Tpo -c -o src/nova-Interpreter.obj `if test -f 'src/Interpreter.cpp'; then $(CYGPATH_W) 'src/Interpreter.cpp'; else $(CYGPATH_W) '$(srcdir)/src/Interpreter.cpp'; fi`
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/nova-Interpreter.Tpo src/$(DEPDIR)/nova-Interpreter.Po
#	$(AM_V_CXX)source='src/Interpreter.cpp' object='src/nova-Interpreter.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(nova_CXXFLAGS) $(CXXFLAGS) -c -o src/nova-Interpreter.obj `if test -f 'src/Interpreter.cpp'; then $(CYGPATH_W) 'src/Interpreter.cpp'; else $(CYGPATH_W) '$(srcdir)/src/Interpreter.cpp'; fi`

src/nova-Lexer.o: src/Lexer.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(nova_CXXFLAGS) $(CXXFLAGS) -MT src/nova-Lexer.o -MD -MP -MF src/$(DEPDIR)/nova-Lexer.Tpo -c -o src/nova-Lexer.o `test -f 'src/Lexer.cpp' || echo '$(srcdir)/'`src/Lexer.cpp
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/nova-Lexer.Tpo src/$(DEPDIR)/nova-Lexer.Po
#	$(AM_V_CXX)source='src/Lexer.cpp' object='src/nova-Lexer.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(nova_CXXFLAGS) $(CXXFLAGS) -c -o src/nova-Lexer.o `test -f 'src/Lexer.cpp' || echo '$(srcdir)/'`src/Lexer.cpp

src/nova-Lexer.obj: src/Lexer.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(nova_CXXFLAGS) $(CXXFLAGS) -MT src/nova-Lexer.obj -MD -MP -MF src/$(DEPDIR)/nova-Lexer.Tpo -c -o src/nova-Lexer.obj `if test -f 'src/Lexer.cpp'; then $(CYGPATH_W) 'src/Lexer.cpp'; else $(CYGPATH_W) '$(srcdir)/src/Lexer.cpp'; fi`
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/nova-Lexer.Tpo src/$(DEPDIR)/nova-Lexer.Po
#	$(AM_V_CXX)source='src/Lexer.cpp' object='src/nova-Lexer.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(nova_CXXFLAGS) $(CXXFLAGS) -c -o src/nova-Lexer.obj `if test -f 'src/Lexer.cpp'; then $(CYGPATH_W) 'src/Lexer.cpp'; else $(CYGPATH_W) '$(srcdir)/src/Lexer.cpp'; fi`

src/nova-ParseHelper.o: src/ParseHelper.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(nova_CXXFLAGS) $(CXXFLAGS) -MT src/nova-ParseHelper.o -MD -MP -MF src/$(DEPDIR)/nova-ParseHelper.Tpo -c -o src/nova-ParseHelper.o `test -f 'src/ParseHelper.cpp' || echo '$(srcdir)/'`src/ParseHelper.cpp
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/nova-ParseHelper.Tpo src/$(DEPDIR)/nova-ParseHelper.Po
#	$(AM_V_CXX)source='src/ParseHelper.cpp' object='src/nova-ParseHelper.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(nova_CXXFLAGS) $(CXXFLAGS) -c -o src/nova-ParseHelper.o `test -f 'src/ParseHelper.cpp' || echo '$(srcdir)/'`src/ParseHelper.cpp

src/nova-ParseHelper.obj: src/ParseHelper.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(nova_CXXFLAGS) $(CXXFLAGS) -MT src/nova-ParseHelper.obj -MD -MP -MF src/$(DEPDIR)/nova-ParseHelper.Tpo -c -o src/nova-ParseHelper.obj `if test -f 'src/ParseHelper.cpp'; then $(CYGPATH_W) 'src/ParseHelper.cpp'; else $(CYGPATH_W) '$(srcdir)/src/ParseHelper.cpp'; fi`
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/nova-ParseHelper.Tpo src/$(DEPDIR)/nova-ParseHelper.Po
#	$(AM_V_CXX)source='src/ParseHelper.cpp' object='src/nova-ParseHelper.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(nova_CXXFLAGS) $(CXXFLAGS) -c -o src/nova-ParseHelper.obj `if test -f 'src/ParseHelper.cpp'; then $(CYGPATH_W) 'src/ParseHelper.cpp'; else $(CYGPATH_W) '$(srcdir)/src/ParseHelper.cpp'; fi`

src/nova-Parser.o: src/Parser.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(nova_CXXFLAGS) $(CXXFLAGS) -MT src/nova-Parser.o -MD -MP -MF src/$(DEPDIR)/nova-Parser.Tpo -c -o src/nova-Parser.o `test -f 'src/Parser.cpp' || echo '$(srcdir)/'`src/Parser.cpp
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/nova-Parser.Tpo src/$(DEPDIR)/nova-Parser.Po
#	$(AM_V_CXX)source='src/Parser.cpp' object='src/nova-Parser.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(nova_CXXFLAGS) $(CXXFLAGS) -c -o src/nova-Parser.o `test -f 'src/Parser.cpp' || echo '$(srcdir)/'`src/Parser.cpp

src/nova-Parser.obj: src/Parser.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(nova_CXXFLAGS) $(CXXFLAGS) -MT src/nova-Parser.obj -MD -MP -MF src/$(DEPDIR)/nova-Parser.Tpo -c -o src/nova-Parser.obj `if test -f 'src/Parser.cpp'; then $(CYGPATH_W) 'src/Parser.cpp'; else $(CYGPATH_W) '$(srcdir)/src/Parser.cpp'; fi`
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/nova-Parser.Tpo src/$(DEPDIR)/nova-Parser.Po
#	$(AM_V_CXX)source='src/Parser.cpp' object='src/nova-Parser.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(nova_CXXFLAGS) $(CXXFLAGS) -c -o src/nova-Parser.obj `if test -f 'src/Parser.cpp'; then $(CYGPATH_W) 'src/Parser.cpp'; else $(CYGPATH_W) '$(srcdir)/src/Parser.cpp'; fi`

src/nova-Position.o: src/Position.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(nova_CXXFLAGS) $(CXXFLAGS) -MT src/nova-Position.o -MD -MP -MF src/$(DEPDIR)/nova-Position.Tpo -c -o src/nova-Position.o `test -f 'src/Position.cpp' || echo '$(srcdir)/'`src/Position.cpp
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/nova-Position.Tpo src/$(DEPDIR)/nova-Position.Po
#	$(AM_V_CXX)source='src/Position.cpp' object='src/nova-Position.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(nova_CXXFLAGS) $(CXXFLAGS) -c -o src/nova-Position.o `test -f 'src/Position.cpp' || echo '$(srcdir)/'`src/Position.cpp

src/nova-Position.obj: src/Position.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(nova_CXXFLAGS) $(CXXFLAGS) -MT src/nova-Position.obj -MD -MP -MF src/$(DEPDIR)/nova-Position.Tpo -c -o src/nova-Position.obj `if test -f 'src/Position.cpp'; then $(CYGPATH_W) 'src/Position.cpp'; else $(CYGPATH_W) '$(srcdir)/src/Position.cpp'; fi`
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/nova-Position.Tpo src/$(DEPDIR)/nova-Position.Po
#	$(AM_V_CXX)source='src/Position.cpp' object='src/nova-Position.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(nova_CXXFLAGS) $(CXXFLAGS) -c -o src/nova-Position.obj `if test -f 'src/Position.cpp'; then $(CYGPATH_W) 'src/Position.cpp'; else $(CYGPATH_W) '$(srcdir)/src/Position.cpp'; fi`

src/nova-shell.o: src/shell.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(nova_CXXFLAGS) $(CXXFLAGS) -MT src/nova-shell.o -MD -MP -MF src/$(DEPDIR)/nova-shell.Tpo -c -o src/nova-shell.o `test -f 'src/shell.cpp' || echo '$(srcdir)/'`src/shell.cpp
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/nova-shell.Tpo src/$(DEPDIR)/nova-shell.Po
#	$(AM_V_CXX)source='src/shell.cpp' object='src/nova-shell.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(nova_CXXFLAGS) $(CXXFLAGS) -c -o src/nova-shell.o `test -f 'src/shell.cpp' || echo '$(srcdir)/'`src/shell.cpp

src/nova-shell.obj: src/shell.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(nova_CXXFLAGS) $(CXXFLAGS) -MT src/nova-shell.obj -MD -MP -MF src/$(DEPDIR)/nova-shell.Tpo -c -o src/nova-shell.obj `if test -f 'src/shell.cpp'; then $(CYGPATH_W) 'src/shell.cpp'; else $(CYGPATH_W) '$(srcdir)/src/shell.cpp'; fi`
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/nova-shell.Tpo src/$(DEPDIR)/nova-shell.Po
#	$(AM_V_CXX)source='src/shell.cpp' object='src/nova-shell.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(nova_CXXFLAGS) $(CXXFLAGS) -c -o src/nova-shell.obj `if test -f 'src/shell.cpp'; then $(CYGPATH_W) 'src/shell.cpp'; else $(CYGPATH_W) '$(srcdir)/src/shell.cpp'; fi`

src/nova-Statement.o: src/Statement.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(nova_CXXFLAGS) $(CXXFLAGS) -MT src/nova-Statement.o -MD -MP -MF src/$(DEPDIR)/nova-Statement.Tpo -c -o src/nova-Statement.o `test -f 'src/Statement.cpp' || echo '$(srcdir)/'`src/Statement.cpp
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/nova-Statement.Tpo src/$(DEPDIR)/nova-Statement.Po
#	$(AM_V_CXX)source='src/Statement.cpp' object='src/nova-Statement.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(nova_CXXFLAGS) $(CXXFLAGS) -c -o src/nova-Statement.o `test -f 'src/Statement.cpp' || echo '$(srcdir)/'`src/Statement.cpp

src/nova-Statement.obj: src/Statement.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(nova_CXXFLAGS) $(CXXFLAGS) -MT src/nova-Statement.obj -MD -MP -MF src/$(DEPDIR)/nova-Statement.Tpo -c -o src/nova-Statement.obj `if test -f 'src/Statement.cpp'; then $(CYGPATH_W) 'src/Statement.cpp'; else $(CYGPATH_W) '$(srcdir)/src/Statement.cpp'; fi`
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/nova-Statement.Tpo src/$(DEPDIR)/nova-Statement.Po
#	$(AM_V_CXX)source='src/Statement.cpp' object='src/nova-Statement.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(nova_CXXFLAGS) $(CXXFLAGS) -c -o src/nova-Statement.obj `if test -f 'src/Statement.cpp'; then $(CYGPATH_W) 'src/Statement.cpp'; else $(CYGPATH_W) '$(srcdir)/src/Statement.cpp'; fi`

src/nova-SymbolTable.o: src/SymbolTable.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(nova_CXXFLAGS) $(CXXFLAGS) -MT src/nova-SymbolTable.o -MD -MP -MF src/$(DEPDIR)/nova-SymbolTable.Tpo -c -o src/nova-SymbolTable.o `test -f 'src/SymbolTable.cpp' || echo '$(srcdir)/'`src/SymbolTable.cpp
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/nova-SymbolTable.Tpo src/$(DEPDIR)/nova-SymbolTable.Po
#	$(AM_V_CXX)source='src/SymbolTable.cpp' object='src/nova-SymbolTable.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(nova_CXXFLAGS) $(CXXFLAGS) -c -o src/nova-SymbolTable.o `test -f 'src/SymbolTable.cpp' || echo '$(srcdir)/'`src/SymbolTable.cpp

src/nova-SymbolTable.obj: src/SymbolTable.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(nova_CXXFLAGS) $(CXXFLAGS) -MT src/nova-SymbolTable.obj -MD -MP -MF src/$(DEPDIR)/nova-SymbolTable.Tpo -c -o src/nova-SymbolTable.obj `if test -f 'src/SymbolTable.cpp'; then $(CYGPATH_W) 'src/SymbolTable.cpp'; else $(CYGPATH_W) '$(srcdir)/src/SymbolTable.cpp'; fi`
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/nova-SymbolTable.Tpo src/$(DEPDIR)/nova-SymbolTable.Po
#	$(AM_V_CXX)source='src/SymbolTable.cpp' object='src/nova-SymbolTable.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(nova_CXXFLAGS) $(CXXFLAGS) -c -o src/nova-SymbolTable.obj `if test -f 'src/SymbolTable.cpp'; then $(CYGPATH_W) 'src/SymbolTable.cpp'; else $(CYGPATH_W) '$(srcdir)/src/SymbolTable.cpp'; fi`

src/nova-Token.o: src/Token.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(nova_CXXFLAGS) $(CXXFLAGS) -MT src/nova-Token.o -MD -MP -MF src/$(DEPDIR)/nova-Token.Tpo -c -o src/nova-Token.o `test -f 'src/Token.cpp' || echo '$(srcdir)/'`src/Token.cpp
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/nova-Token.Tpo src/$(DEPDIR)/nova-Token.Po
#	$(AM_V_CXX)source='src/Token.cpp' object='src/nova-Token.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(nova_CXXFLAGS) $(CXXFLAGS) -c -o src/nova-Token.o `test -f 'src/Token.cpp' || echo '$(srcdir)/'`src/Token.cpp

src/nova-Token.obj: src/Token.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(nova_CXXFLAGS) $(CXXFLAGS) -MT src/nova-Token.obj -MD -MP -MF src/$(DEPDIR)/nova-Token.Tpo -c -o src/nova-Token.obj `if test -f 'src/Token.cpp'; then $(CYGPATH_W) 'src/Token.cpp'; else $(CYGPATH_W) '$(srcdir)/src/Token.cpp'; fi`
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/nova-Token.Tpo src/$(DEPDIR)/nova-Token.Po
#	$(AM_V_CXX)source='src/Token.cpp' object='src/nova-Token.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(nova_CXXFLAGS) $(CXXFLAGS) -c -o src/nova-Token.obj `if test -f 'src/Token.cpp'; then $(CYGPATH_W) 'src/Token.cpp'; else $(CYGPATH_W) '$(srcdir)/src/Token.cpp'; fi`

src/nova-types.o: src/types.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(nova_CXXFLAGS) $(CXXFLAGS) -MT src/nova-types.o -MD -MP -MF src/$(DEPDIR)/nova-types.Tpo -c -o src/nova-types.o `test -f 'src/types.cpp' || echo '$(srcdir)/'`src/types.cpp
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/nova-types.Tpo src/$(DEPDIR)/nova-types.Po
#	$(AM_V_CXX)source='src/types.cpp' object='src/nova-types.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(nova_CXXFLAGS) $(CXXFLAGS) -c -o src/nova-types.o `test -f 'src/types.cpp' || echo '$(srcdir)/'`src/types.cpp

src/nova-types.obj: src/types.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(nova_CXXFLAGS) $(CXXFLAGS) -MT src/nova-types.obj -MD -MP -MF src/$(DEPDIR)/nova-types.Tpo -c -o src/nova-types.obj `if test -f 'src/types.cpp'; then $(CYGPATH_W) 'src/types.cpp'; else $(CYGPATH_W) '$(srcdir)/src/types.cpp'; fi`
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/nova-types.Tpo src/$(DEPDIR)/nova-types.Po
#	$(AM_V_CXX)source='src/types.cpp' object='src/nova-types.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(nova_CXXFLAGS) $(CXXFLAGS) -c -o src/nova-types.obj `if test -f 'src/types.cpp'; then $(CYGPATH_W) 'src/types.cpp'; else $(CYGPATH_W) '$(srcdir)/src/types.cpp'; fi`

ID: $(am__tagged_files)
	$(am__define_uniq_tagged_files); mkid -fID $$unique
tags: tags-am
TAGS: tags

tags-am: $(TAGS_DEPENDENCIES) $(am__tagged_files)
	set x; \
	here=`pwd`; \
	$(am__define_uniq_tagged_files); \
	shift; \
	if test -z "$(ETAGS_ARGS)$$*$$unique"; then :; else \
	  test -n "$$unique" || unique=$$empty_fix; \
	  if test $$# -gt 0; then \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      "$$@" $$unique; \
	  else \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      $$unique; \
	  fi; \
	fi
ctags: ctags-am

CTAGS: ctags
ctags-am: $(TAGS_DEPENDENCIES) $(am__tagged_files)
	$(am__define_uniq_tagged_files); \
	test -z "$(CTAGS_ARGS)$$unique" \
	  || $(CTAGS) $(CTAGSFLAGS) $(AM_CTAGSFLAGS) $(CTAGS_ARGS) \
	     $$unique

GTAGS:
	here=`$(am__cd) $(top_builddir) && pwd` \
	  && $(am__cd) $(top_srcdir) \
	  && gtags -i $(GTAGS_ARGS) "$$here"
cscope: cscope.files
	test ! -s cscope.files \
	  || $(CSCOPE) -b -q $(AM_CSCOPEFLAGS) $(CSCOPEFLAGS) -i cscope.files $(CSCOPE_ARGS)
clean-cscope:
	-rm -f cscope.files
cscope.files: clean-cscope cscopelist
cscopelist: cscopelist-am

cscopelist-am: $(am__tagged_files)
	list='$(am__tagged_files)'; \
	case "$(srcdir)" in \
	  [\\/]* | ?:[\\/]*) sdir="$(srcdir)" ;; \
	  *) sdir=$(subdir)/$(srcdir) ;; \
	esac; \
	for i in $$list; do \
	  if test -f "$$i"; then \
	    echo "$(subdir)/$$i"; \
	  else \
	    echo "$$sdir/$$i"; \
	  fi; \
	done >> $(top_builddir)/cscope.files

distclean-tags:
	-rm -f TAGS ID GTAGS GRTAGS GSYMS GPATH tags
	-rm -f cscope.out cscope.in.out cscope.po.out cscope.files

distdir: $(DISTFILES)
	$(am__remove_distdir)
	test -d "$(distdir)" || mkdir "$(distdir)"
	@srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	topsrcdirstrip=`echo "$(top_srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	list='$(DISTFILES)'; \
	  dist_files=`for file in $$list; do echo $$file; done | \
	  sed -e "s|^$$srcdirstrip/||;t" \
	      -e "s|^$$topsrcdirstrip/|$(top_builddir)/|;t"`; \
	case $$dist_files in \
	  */*) $(MKDIR_P) `echo "$$dist_files" | \
			   sed '/\//!d;s|^|$(distdir)/|;s,/[^/]*$$,,' | \
			   sort -u` ;; \
	esac; \
	for file in $$dist_files; do \
	  if test -f $$file || test -d $$file; then d=.; else d=$(srcdir); fi; \
	  if test -d $$d/$$file; then \
	    dir=`echo "/$$file" | sed -e 's,/[^/]*$$,,'`; \
	    if test -d "$(distdir)/$$file"; then \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    if test -d $(srcdir)/$$file && test $$d != $(srcdir); then \
	      cp -fpR $(srcdir)/$$file "$(distdir)$$dir" || exit 1; \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    cp -fpR $$d/$$file "$(distdir)$$dir" || exit 1; \
	  else \
	    test -f "$(distdir)/$$file" \
	    || cp -p $$d/$$file "$(distdir)/$$file" \
	    || exit 1; \
	  fi; \
	done
	-test -n "$(am__skip_mode_fix)" \
	|| find "$(distdir)" -type d ! -perm -755 \
		-exec chmod u+rwx,go+rx {} \; -o \
	  ! -type d ! -perm -444 -links 1 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -400 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -444 -exec $(install_sh) -c -m a+r {} {} \; \
	|| chmod -R a+r "$(distdir)"
dist-gzip: distdir
	tardir=$(distdir) && $(am__tar) | eval GZIP= gzip $(GZIP_ENV) -c >$(distdir).tar.gz
	$(am__post_remove_distdir)

dist-bzip2: distdir
	tardir=$(distdir) && $(am__tar) | BZIP2=$${BZIP2--9} bzip2 -c >$(distdir).tar.bz2
	$(am__post_remove_distdir)

dist-lzip: distdir
	tardir=$(distdir) && $(am__tar) | lzip -c $${LZIP_OPT--9} >$(distdir).tar.lz
	$(am__post_remove_distdir)

dist-xz: distdir
	tardir=$(distdir) && $(am__tar) | XZ_OPT=$${XZ_OPT--e} xz -c >$(distdir).tar.xz
	$(am__post_remove_distdir)

dist-tarZ: distdir
	@echo WARNING: "Support for distribution archives compressed with" \
		       "legacy program 'compress' is deprecated." >&2
	@echo WARNING: "It will be removed altogether in Automake 2.0" >&2
	tardir=$(distdir) && $(am__tar) | compress -c >$(distdir).tar.Z
	$(am__post_remove_distdir)

dist-shar: distdir
	@echo WARNING: "Support for shar distribution archives is" \
	               "deprecated." >&2
	@echo WARNING: "It will be removed altogether in Automake 2.0" >&2
	shar $(distdir) | eval GZIP= gzip $(GZIP_ENV) -c >$(distdir).shar.gz
	$(am__post_remove_distdir)

dist-zip: distdir
	-rm -f $(distdir).zip
	zip -rq $(distdir).zip $(distdir)
	$(am__post_remove_distdir)

dist dist-all:
	$(MAKE) $(AM_MAKEFLAGS) $(DIST_TARGETS) am__post_remove_distdir='@:'
	$(am__post_remove_distdir)

# This target untars the dist file and tries a VPATH configuration.  Then
# it guarantees that the distribution is self-contained by making another
# tarfile.
distcheck: dist
	case '$(DIST_ARCHIVES)' in \
	*.tar.gz*) \
	  eval GZIP= gzip $(GZIP_ENV) -dc $(distdir).tar.gz | $(am__untar) ;;\
	*.tar.bz2*) \
	  bzip2 -dc $(distdir).tar.bz2 | $(am__untar) ;;\
	*.tar.lz*) \
	  lzip -dc $(distdir).tar.lz | $(am__untar) ;;\
	*.tar.xz*) \
	  xz -dc $(distdir).tar.xz | $(am__untar) ;;\
	*.tar.Z*) \
	  uncompress -c $(distdir).tar.Z | $(am__untar) ;;\
	*.shar.gz*) \
	  eval GZIP= gzip $(GZIP_ENV) -dc $(distdir).shar.gz | unshar ;;\
	*.zip*) \
	  unzip $(distdir).zip ;;\
	esac
	chmod -R a-w $(distdir)
	chmod u+w $(distdir)
	mkdir $(distdir)/_build $(distdir)/_build/sub $(distdir)/_inst
	chmod a-w $(distdir)
	test -d $(distdir)/_build || exit 0; \
	dc_install_base=`$(am__cd) $(distdir)/_inst && pwd | sed -e 's,^[^:\\/]:[\\/],/,'` \
	  && dc_destdir="$${TMPDIR-/tmp}/am-dc-$$$$/" \
	  && am__cwd=`pwd` \
	  && $(am__cd) $(distdir)/_build/sub \
	  && ../../configure \
	    $(AM_DISTCHECK_CONFIGURE_FLAGS) \
	    $(DISTCHECK_CONFIGURE_FLAGS) \
	    --srcdir=../.. --prefix="$$dc_install_base" \
	  && $(MAKE) $(AM_MAKEFLAGS) \
	  && $(MAKE) $(AM_MAKEFLAGS) dvi \
	  && $(MAKE) $(AM_MAKEFLAGS) check \
	  && $(MAKE) $(AM_MAKEFLAGS) install \
	  && $(MAKE) $(AM_MAKEFLAGS) installcheck \
	  && $(MAKE) $(AM_MAKEFLAGS) uninstall \
	  && $(MAKE) $(AM_MAKEFLAGS) distuninstallcheck_dir="$$dc_install_base" \
	        distuninstallcheck \
	  && chmod -R a-w "$$dc_install_base" \
	  && ({ \
	       (cd ../.. && umask 077 && mkdir "$$dc_destdir") \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" install \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" uninstall \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" \
	            distuninstallcheck_dir="$$dc_destdir" distuninstallcheck; \
	      } || { rm -rf "$$dc_destdir"; exit 1; }) \
	  && rm -rf "$$dc_destdir" \
	  && $(MAKE) $(AM_MAKEFLAGS) dist \
	  && rm -rf $(DIST_ARCHIVES) \
	  && $(MAKE) $(AM_MAKEFLAGS) distcleancheck \
	  && cd "$$am__cwd" \
	  || exit 1
	$(am__post_remove_distdir)
	@(echo "$(distdir) archives ready for distribution: "; \
	  list='$(DIST_ARCHIVES)'; for i in $$list; do echo $$i; done) | \
	  sed -e 1h -e 1s/./=/g -e 1p -e 1x -e '$$p' -e '$$x'
distuninstallcheck:
	@test -n '$(distuninstallcheck_dir)' || { \
	  echo 'ERROR: trying to run $@ with an empty' \
	       '$$(distuninstallcheck_dir)' >&2; \
	  exit 1; \
	}; \
	$(am__cd) '$(distuninstallcheck_dir)' || { \
	  echo 'ERROR: cannot chdir into $(distuninstallcheck_dir)' >&2; \
	  exit 1; \
	}; \
	test `$(am__distuninstallcheck_listfiles) | wc -l` -eq 0 \
	   || { echo "ERROR: files left after uninstall:" ; \
	        if test -n "$(DESTDIR)"; then \
	          echo "  (check DESTDIR support)"; \
	        fi ; \
	        $(distuninstallcheck_listfiles) ; \
	        exit 1; } >&2
distcleancheck: distclean
	@if test '$(srcdir)' = . ; then \
	  echo "ERROR: distcleancheck can only run from a VPATH build" ; \
	  exit 1 ; \
	fi
	@test `$(distcleancheck_listfiles) | wc -l` -eq 0 \
	  || { echo "ERROR: files left in build directory after distclean:" ; \
	       $(distcleancheck_listfiles) ; \
	       exit 1; } >&2
check-am: all-am
check: check-am
all-am: Makefile $(PROGRAMS)
installdirs:
	for dir in "$(DESTDIR)$(bindir)"; do \
	  test -z "$$dir" || $(MKDIR_P) "$$dir"; \
	done
install: install-am
install-exec: install-exec-am
install-data: install-data-am
uninstall: uninstall-am

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am

installcheck: installcheck-am
install-strip:
	if test -z '$(STRIP)'; then \
	  $(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	    install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	      install; \
	else \
	  $(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	    install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	    "INSTALL_PROGRAM_ENV=STRIPPROG='$(STRIP)'" install; \
	fi
mostlyclean-generic:

clean-generic:

distclean-generic:
	-test -z "$(CONFIG_CLEAN_FILES)" || rm -f $(CONFIG_CLEAN_FILES)
	-test . = "$(srcdir)" || test -z "$(CONFIG_CLEAN_VPATH_FILES)" || rm -f $(CONFIG_CLEAN_VPATH_FILES)
	-rm -f src/$(DEPDIR)/$(am__dirstamp)
	-rm -f src/$(am__dirstamp)

maintainer-clean-generic:
	@echo "This command is intended for maintainers to use"
	@echo "it deletes files that may require special tools to rebuild."
clean: clean-am

clean-am: clean-binPROGRAMS clean-generic mostlyclean-am

distclean: distclean-am
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -rf src/$(DEPDIR)
	-rm -f Makefile
distclean-am: clean-am distclean-compile distclean-generic \
	distclean-tags

dvi: dvi-am

dvi-am:

html: html-am

html-am:

info: info-am

info-am:

install-data-am:

install-dvi: install-dvi-am

install-dvi-am:

install-exec-am: install-binPROGRAMS

install-html: install-html-am

install-html-am:

install-info: install-info-am

install-info-am:

install-man:

install-pdf: install-pdf-am

install-pdf-am:

install-ps: install-ps-am

install-ps-am:

installcheck-am:

maintainer-clean: maintainer-clean-am
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -rf $(top_srcdir)/autom4te.cache
	-rm -rf src/$(DEPDIR)
	-rm -f Makefile
maintainer-clean-am: distclean-am maintainer-clean-generic

mostlyclean: mostlyclean-am

mostlyclean-am: mostlyclean-compile mostlyclean-generic

pdf: pdf-am

pdf-am:

ps: ps-am

ps-am:

uninstall-am: uninstall-binPROGRAMS

.MAKE: install-am install-strip

.PHONY: CTAGS GTAGS TAGS all all-am am--refresh check check-am clean \
	clean-binPROGRAMS clean-cscope clean-generic cscope \
	cscopelist-am ctags ctags-am dist dist-all dist-bzip2 \
	dist-gzip dist-lzip dist-shar dist-tarZ dist-xz dist-zip \
	distcheck distclean distclean-compile distclean-generic \
	distclean-tags distcleancheck distdir distuninstallcheck dvi \
	dvi-am html html-am info info-am install install-am \
	install-binPROGRAMS install-data install-data-am install-dvi \
	install-dvi-am install-exec install-exec-am install-html \
	install-html-am install-info install-info-am install-man \
	install-pdf install-pdf-am install-ps install-ps-am \
	install-strip installcheck installcheck-am installdirs \
	maintainer-clean maintainer-clean-generic mostlyclean \
	mostlyclean-compile mostlyclean-generic pdf pdf-am ps ps-am \
	tags tags-am uninstall uninstall-am uninstall-binPROGRAMS

.PRECIOUS: Makefile


# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
