name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: aclocal
      run: aclocal
    - name: automake
      run: automake --add-missing
    - name: autoreconf
      run: autoreconf
    - name: configure
      run: ./configure
    - name: make
      run: make
